services:
  inmobiliaria-crm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inmobiliaria-crm-2026
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
